POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "New client",
  "email": "new@client.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "8d34617d-81ac-4e5e-ada3-777c33087c46"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_from_id": "912ca3ff-59d4-4640-acd8-76eb1faf0dbe",
  "account_to_id": "31fb673a-012a-4cfc-8dc9-7a9ad0219437",
  "amount": 10
}

########################################

GET http://localhost:3003/hello HTTP/1.1
Content-Type: application/json

### get john's account

GET http://localhost:3003/accounts/912ca3ff-59d4-4640-acd8-76eb1faf0dbe HTTP/1.1
Content-Type: application/json

### get jane's account

GET http://localhost:3003/accounts/31fb673a-012a-4cfc-8dc9-7a9ad0219437 HTTP/1.1
Content-Type: application/json