POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "New client",
  "email": "new@client.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "aa4e6c5a-ac95-4191-aac6-fcc94c22d8f7"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_from_id": "2629a6aa-ffae-4563-a8d8-2058eae570df",
  "account_to_id": "bf4beaf3-6e8b-4ece-8d91-f4a63f9d5105",
  "amount": 10
}